#!/bin/sh
#deploy="false"
deploy="true"

image=final_Resource
version=1.0-SNAPSHOT
latest=true

#OPTIONS="--no-cache --force-rm"
#OPTIONS="--no-cache"
#OPTIONS="--force-rm"
OPTIONS=""

docker build ${OPTIONS} -t keyur/${image}:1.0-SNAPSHOT .
if [ "$?" -eq 0 ] && [ ${deploy} == "true" ]; then
    docker push keyur/${image}:1.0-SNAPSHOT
    if [ "$latest" == "true" ]; then
        docker tag keyur/${image}:1.0-SNAPSHOT keyur/${image}:latest
        docker push keyur/${image}:latest
    fi
fi