#!/bin/sh
mvn clean package && docker build -t keyur/final_Resource .
docker rm -f final_Resource 2>/dev/null || true && docker run -it --name final_Resource -p 8080:8080 -p 4848:4848 -p 8181:8181 --name final_Resource keyur/final_Resource
